In [1]:
from agent import RandomAgent, MiniMaxAgent
from sim import simulate 
from tictactoe import Board2D
import numpy as np

In [2]:
def simple_eval(node, player):
    board = node.state
    
    if board.get_winner() == player:
        return 100
    elif board.get_winner() == -player:
        return -100
    else:
        return 0

In [3]:
rand = RandomAgent()
mini = MiniMaxAgent(simple_eval, depth=9, name='MiniMaxAgent', using_ab_pruning=True)

board = Board2D(board_size=3)

In [5]:
simulate(board, rand, mini, num_sims=100, display=True)

========= move 0 =========
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
=========        =========
========= move 1 =========
[[ 0. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
=========        =========
========= move 2 =========
[[ 1. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
=========        =========
========= move 3 =========
[[ 1. -1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
=========        =========
========= move 4 =========
[[ 1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
=========        =========
========= move 5 =========
[[ 1. -1. -1.]
 [ 1.  0.  0.]
 [ 0. -1.  0.]]
=========        =========
========= move 6 =========
[[ 1. -1. -1.]
 [ 1.  1.  0.]
 [ 0. -1.  0.]]
=========        =========
========= move 7 =========
[[ 1. -1. -1.]
 [ 1.  1.  0.]
 [ 0. -1. -1.]]
=========        =========
========= move 8 =========
[[ 1. -1. -1.]
 [ 1.  1.  1.]
 [ 0. -1. -1.]]
=========        =========
========= move 0 =========
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
=========        =========


KeyboardInterrupt: 

In [13]:
mini1 = MiniMaxAgent(simple_eval, depth=9, name='mini1')
mini2 = MiniMaxAgent(simple_eval, depth=9, name='mini2')

board = Board2D(board_size=3)
simulate(board, mini1, mini2, num_sims=100, display=False)

{'draw': 100, 'mini1': 0, 'mini2': 0}

This agent playing against itself will always draw and never loses to a random agent, which makes me believe it's optimal for 3x3.